Horst Otto Hausverwaltungs GmbH

Gutenbergallee 27, 63538 Großkrotzenburg

= Hausordnung

WEG Kolbershecke 2
63457 Hanau Großauheim

Eine vertrauensvolle Hausgemeinschaft kann nur bestehen, wenn von allen, Eigentümer und Mietern, weitgehend Rücksicht aufeinander genommen und die Hausordnung eingehalten wird.
Jeder ist daher verpflichtet, die nachstehenden Punkte einzuhalten.

1. Das Sonder- und das gemeinschaftliche Eigentum ist ordentlich und sachgemäß zu behandeln.
Beschädigungen der Versorgungsleitungen und sonstiger Einrichtungen sind zu vermeiden.
Störungen sind dem Hausverwalter umgehend zu melden.
__Die Kontaktdaten der Hausverwaltung hängen am schwarzen Brett im Keller-Abgang aus.__

2. Ist die Wohnung längere Zeit unbenutzt, sollte der Wohnungsinhaber seine Wohnungsschlüssel bei einer Person seines Vertrauens hinterlegen, un ddem Beirat bzw. Verwalter dies bekannt __geben__.

3. Die zur Wohnung gehörenden Vorplätze sind frei und sauber zu halten und bei Bedarf zu reinigen.

4. Bei An- oder Ablieferung schmutzverursachender Materialien sind entstehende Verunreinigungen vom Empfänger bzw. Absender sofort zu beseitigen.

5. Zur Abfallbeseitigung dürfen nur die Mülltonnen benutzt werden.
Auf eine konsequente Trennung des Mülls ist zu achten.
Sondermüll und Sperrmüll gehören nicht in diese Behälter und dürfen auch nicht auf dem Abstellplatz für Mülltonnen gelagert werden.

6. Die Benutzung des Trockenraumes ist bei Bedarf zu regeln.

7. Ruhestörender Lärm ist zu vermeiden.
Die Mittagspause von 13 bis 15 Uhr und die Nachtruhe von 22 bis 6 Uhr __ist__ einzuhalten.
Radio- und Fernsehgeräte sind auf Zimmerlautstärke einzustellen.
An Sonn- und Feiertagen ist generell ruhestörender Lärm zu unterlassen.

8. Das Ausklopfen von Teppichen etc. ist an dem dafür vorgesehenen Platz nur werktags, unter Berücksichtigung der unter Punkt 7 genannten Ruhezeiten, erlaubt.

9. Tierhaltung über einen längeren Zeitraum darf nur mit Zustimmung der Eigentümer erfolgen.
Die Zustimmung kann jederzeit widerrufen werden.
Sollten Sie Ihre Wohnung vermieten, achten Sie bitte besonders hierauf.

10. Das Abstellen von Fahrrädern und Tretrollern etc. ist auf Dauer in den Kellergängen und im Treppenhaus nicht __gestattet__.
Hierfür ist der Fahrradkeller zu benutzen.
Kinderwagen können auf dem dafür vorgesehenen Platz im Keller abgestellt werden.
Möbel o.ä. dürfen im Fahrradkeller und im Waschkeller nicht abgestellt werden.

11. Der Keller darf nicht mit offenem Licht betreten, leicht entzündliche Gegenstände dort nicht aufbewahrt werden.
Die Räume sollten gut zu übersehen un dleicht zugänglich sein.
Im Interesse der allgemeinen Ordnung und Sicherheit sind alle behördlichen und polizeilichen Vorschriften auch dann zu beachten, wenn hierüber nichts ausdrücklich gesagt ist.

12. Der Abstellplatz in der Sammelgarage ist nur zum Unterstellen von PKWs und/ oder Krafträdern vorgesehen.
Das Lagern von Gegenständen aller Art auf dem Tiefgaragenplatz ist untersagt.
Insbesondere dürfen keine feuergefährlichen Gegenstände oder Treibstoff gelagert werden.

13. Die Treppenhausfenster sind bei Sturm, Regen oder Frost geschlossen zu halten.
Kellerfenster sind im Winter zu schließen.
Die Gitter an den Kellerfenstern haben ständig verschlossen zu sein.

14. Wäschetrocknen auf dem Balkon ist bis Geländerhöhe erlaubt.
Blumentöpfe bzw. -Kästen dürfen nur in gut gesichertem Zustand gegen herabfallen und gegen ablaufen von Gießwasser auf den Fensterbänken und an bzw. auf den Balkongeländern abgestellt werden.

15. Di eHaustür ist geschlossen z uhalten.
Ebenfalls ist das Garagentor geschlossen zu halten.
Jeder Hausbewohner achtet im eigenene Interesse darauf.

16. Reparaturen und Veränderungen an den Gemeinschaftsantennen können nur durch den Verwalter veranlasst werden.
Das Anbringen von Außenantennen ist nicht gestattet.

17. Die Heizung wird ausschließlich von der Servicefirma bedient.
Der Außenschalter darf nur in Notfällen betätigt werden.


Eine Änderung der Hausordnung bleibt dem Mehrheitsbeschluss der Eigentümer vorbehalten.
Die Hausordnung ist zum Bestandteil jeden Mietvertrages zu machen.

Großkrotzenburg, den 17.04.2008
