
= Hausordnung

WEG Kolbershecke 2

63457 Hanau Großauheim

Eine vertrauensvolle Hausgemeinschaft kann nur bestehen, wenn von allen,
Eigentümern und Mietern, Rücksicht aufeinander genommen und die Hausordnung
eingehalten wird. Jeder ist daher zur Einhaltung verpflichtet.

1. Das Sonder- und das gemeinschaftliche Eigentum ist ordentlich und sachgemäß
zu behandeln. Der Aussenbereich ist in gepflegtem Zustand zu halten.
Beschädigungen der Versorgungsleitungen und sonstiger Einrichtungen sind zu
vermeiden.  Störungen sind dem Hausverwalter umgehend zu melden.
Die Kontaktdaten hängen am schwarzen Brett im Keller-Abgang aus.

2. Ist die Wohnung längere Zeit unbenutzt, sollte der Wohnungsinhaber seine
Wohnungsschlüssel bei einer Person seines Vertrauens hinterlegen, und dem Beirat
bzw. Verwalter dies bekannt geben.

3. Bei An- oder Ablieferung schmutzverursachender Materialien sind entstehende
Verunreinigungen sofort zu beseitigen.

4. Zur Abfallbeseitigung dürfen nur die Mülltonnen benutzt werden.
Auf eine konsequente Trennung des Mülls ist zu achten.
Sondermüll und Sperrmüll gehören nicht in diese Behälter und dürfen auch nicht
auf dem Abstellplatz für Mülltonnen gelagert werden.

5. Mittags- und Nachtruhe
Die Mittagsruhe von 13 bis 15 Uhr und die Nachtruhe von 22 bis 6 Uhr ist
einzuhalten.

6. Ruhestörung und Lärmbelästigung
Generell ist ruhestörender Lärm zu unterlassen.
Radio- und Fernsehgeräte sind auf Zimmerlautstärke einzustellen.
An Sonn- und Feiertagen ist generell ruhestörender Lärm zu unterlassen.
Türen sind leise zu schließen.

7. Hundehaltung ist grundsätzlich erlaubt, die Zustimmung kann jedoch aus
besonderem Grund widerrufen werden.
Besondere Gründe sind in der Regel Lärmbelästigung und Gefährdung von
Mitbewohnern.

8. Haus- und Hofeingänge, Treppen und Flure sind als Fluchtwege grundsätzlich
freizuhalten.
Aus diesem Grund ist im Treppenhaus das Abstellen von Gegenständen aller Art
untersagt.
Kinderwagen können auf dem dafür vorgesehenen Platz im Keller abgestellt werden.
Für Fahrräder und Tretroller etc. ist der Fahrradkeller zu benutzen.
Möbel o.ä. dürfen im Fahrradkeller und im Waschkeller nicht abgestellt werden.

9. Die Tiefgarage ist nur zum Unterstellen von PKWs und/ oder Krafträdern
vorgesehen.
Das Lagern von Gegenständen aller Art auf dem Tiefgaragenplatz ist untersagt.
Insbesondere dürfen keine feuergefährlichen Gegenstände oder Treibstoff gelagert
werden.
Im Interesse der allgemeinen Ordnung und Sicherheit sind alle behördlichen und
polizeilichen Vorschriften auch dann zu beachten, wenn hierüber nichts
ausdrücklich gesagt ist.

10. Die Treppenhausfenster sind bei Sturm, Regen oder Frost geschlossen zu
halten.
Kellerfenster sind im Winter zu schließen.
Die Gitter an den Kellerfenstern und Lichtschächten sind ständig geschlossen zu
halten.

11. Wäschetrocknen auf dem Balkon ist bis Geländerhöhe erlaubt.
Blumentöpfe bzw. -kästen dürfen nur in gut gesichertem Zustand gegen Herabfallen
und gegen Ablaufen von Gießwasser auf den Fensterbänken und an bzw. auf den
Balkongeländern abgestellt werden.

12. Alle Außentüren sind stets geschlossen zu halten.
Jeder Hausbewohner achtet im eigenen Interesse darauf.

13. Das Anbringen von Außenantennen ist nicht gestattet.

14. Die Heizung wird ausschließlich von der Servicefirma bedient.
Der Außenschalter darf nur in Notfällen betätigt werden.

15. Grillen mit Brickets, Holz oder Holzkohle ist auf den Balkonen oder auf den
unmittelbar am Gebäude liegenden Flächen nicht erlaubt.

Stand: Juni 2016
